"""Natural Math v5 reference implementation — provenance records.

Records donor attribution for every extracted function.
"""

from __future__ import annotations

from typing import Any

PROVENANCE: dict[str, dict[str, Any]] = {
    "errors.NaturalMathValidationError": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "class NaturalMathValidationError(Exception)",
        "modifications": "renamed from ValidationError to NaturalMathValidationError per spec",
        "reason": "spec Section 6: validation error type",
        "spec_section": "6",
    },
    "records.make_node": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "make_node function",
        "modifications": "cleaned up default values, added type hints",
        "reason": "spec Section 3: node record construction",
        "spec_section": "3",
    },
    "records.die_inert": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "die_inert function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 4: inert death semantics",
        "spec_section": "4",
    },
    "records.die_branch": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "bifurcation parent death inline",
        "modifications": "extracted to named function",
        "reason": "spec Section 14: bifurcation parent death",
        "spec_section": "14",
    },
    "parameters.DEFAULT_PARAMS": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "DEFAULT_PARAMS dict",
        "modifications": "added cluster params from cluster runner donor",
        "reason": "spec Section 5: complete parameter table",
        "spec_section": "5",
    },
    "parameters.validate_params": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "validate_params function (partial)",
        "modifications": "extended to all 38 parameters with full constraint set",
        "reason": "spec Section 5: all constraints, donor had partial validation",
        "spec_section": "5",
    },
    "arithmetic.qdist": {
        "donor": "both runners",
        "donor_location": "qdist function (identical in both)",
        "modifications": "none (identical logic)",
        "reason": "spec Section 7: squared grid distance",
        "spec_section": "7",
    },
    "arithmetic.integer_div": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "integer_div function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 2: integer division",
        "spec_section": "2",
    },
    "arithmetic.sign": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "sign function",
        "modifications": "none",
        "reason": "spec Section 7: sign function",
        "spec_section": "7",
    },
    "arithmetic.dot": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "dot function",
        "modifications": "none",
        "reason": "spec Section 7: dot product",
        "spec_section": "7",
    },
    "randomness.TraceRng": {
        "donor": "both runners",
        "donor_location": "ClusterTraceRng class (identical in both)",
        "modifications": "renamed to TraceRng, extracted to separate module",
        "reason": "spec Section 8: traceable RNG",
        "spec_section": "8",
    },
    "randomness.sample_two": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "sample_two function",
        "modifications": "none",
        "reason": "spec Section 8: random unordered pair",
        "spec_section": "8",
    },
    "validation.validate_nodes": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "validate_nodes function",
        "modifications": "extended with bond symmetry, max bonds, direction check",
        "reason": "spec Section 6: full node validation",
        "spec_section": "6",
    },
    "validation.check_invariants": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "check_invariants function",
        "modifications": "none (identical logic, relocated from invariants.py plan)",
        "reason": "spec Section 6A: runtime invariants",
        "spec_section": "6A",
    },
    "gradient.gradient_direction": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "gradient_direction function",
        "modifications": "extracted deficit computation to helper, cleaned rational arithmetic",
        "reason": "spec Section 10: integer gradient choice",
        "spec_section": "10",
    },
    "gradient.deficit": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "inline in gradient_direction",
        "modifications": "extracted to separate function",
        "reason": "spec Section 9: deficit computation",
        "spec_section": "9",
    },
    "decisions.compute_decision": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "compute_decision function",
        "modifications": "cleaned up, added explicit rng=None validation error",
        "reason": "spec Section 11: contact and decision rules",
        "spec_section": "11",
    },
    "decisions.fallback_direction": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "inline in movement phase",
        "modifications": "extracted to named function",
        "reason": "spec Section 13: fallback direction rules",
        "spec_section": "13",
    },
    "movement.resolve_movement": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "resolve_movement function",
        "modifications": "added reserved_child_positions to blocking check (spec gap closure)",
        "reason": "spec Section 13: movement resolution with reserved child blocking",
        "spec_section": "13",
    },
    "bifurcation.child_directions": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "child_directions function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 15: child direction table",
        "spec_section": "15",
    },
    "bifurcation.can_bifurcate": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "can_bifurcate function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 14: bifurcation eligibility check",
        "spec_section": "14",
    },
    "bifurcation.apply_bifurcation": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "apply_bifurcation function",
        "modifications": "uses pre-assigned child IDs instead of computing next_id internally",
        "reason": "spec Section 14: child-ID assignment must happen in check order",
        "spec_section": "14",
    },
    "pressure.update_pressure": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "update_pressure function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 16: pressure update",
        "spec_section": "16",
    },
    "bonding.apply_bonding": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "apply_bonding function",
        "modifications": "removed redundant allow_bonding check (caller guards this)",
        "reason": "spec Section 17: bonding",
        "spec_section": "17",
    },
    "core_step.run_step": {
        "donor": "natural_math_integer_oracle_runner.py",
        "donor_location": "run_step function",
        "modifications": "reorganized phases, added reserved_child_positions to movement, explicit invariants call",
        "reason": "spec Sections 2-17, 23: full run_step pipeline",
        "spec_section": "12",
    },
    "cluster_initialization.initialize_cluster": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "initialize_cluster function",
        "modifications": "extracted to module, cleaned up imports",
        "reason": "spec Sections 18-19: cluster initialization",
        "spec_section": "18-19",
    },
    "cluster_metrics.compute_metrics": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "compute_metrics function",
        "modifications": "none (identical core logic)",
        "reason": "spec Section 20: cluster metrics",
        "spec_section": "20",
    },
    "cluster_metrics.connected_components": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "connected_components function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 20: connected components",
        "spec_section": "20",
    },
    "cluster_metrics.compute_gini": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "compute_gini function",
        "modifications": "verified formula matches donor",
        "reason": "spec Section 20: integer Gini coefficient",
        "spec_section": "20",
    },
    "cluster_actions.apply_seek": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "apply_seek function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 21: SEEK action",
        "spec_section": "21",
    },
    "cluster_actions.apply_redistribute": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "apply_redistribute function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 21: REDISTRIBUTE action",
        "spec_section": "21",
    },
    "cluster_actions.apply_repair": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "apply_repair function",
        "modifications": "none (identical core logic)",
        "reason": "spec Section 21: REPAIR action",
        "spec_section": "21",
    },
    "cluster_actions.apply_rest": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "apply_rest function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 21: REST action",
        "spec_section": "21",
    },
    "cluster_actions.apply_resource_absorption": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "apply_resource_absorption function",
        "modifications": "none (identical logic)",
        "reason": "spec Section 21: resource absorption",
        "spec_section": "21",
    },
    "cluster_step.cluster_step": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "cluster_step function",
        "modifications": "extracted apply_damage to separate function",
        "reason": "spec Sections 21-22: cluster step pipeline",
        "spec_section": "21-22",
    },
    "cluster_step.apply_damage": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "inline in cluster_step",
        "modifications": "extracted to separate function",
        "reason": "spec Section 22: damage phase",
        "spec_section": "22",
    },
    "cluster.run_cluster": {
        "donor": "natural_math_cluster_oracle_runner.py",
        "donor_location": "new (donor had run_cluster_summary without validation)",
        "modifications": "created wrapper with spec-compliant signature, validation, fresh defaults",
        "reason": "spec Section 2A: run_cluster entry point",
        "spec_section": "2A",
    },
}


def get_provenance() -> dict[str, dict[str, Any]]:
    return dict(PROVENANCE)
